#My first Pipeline
# This pipeline demonstrates running PowerShell commands
trigger: none

pool:
  name: 'TESTVM'

steps:
- task: Bash@3
  displayName: 'Printing my name using Batch'
  inputs:
    targetType: 'inline'
    script: |
      echo "hello,Arshad"