#My first Pipeline
# This pipeline demonstrates running PowerShell commands
trigger: none

pool:
  vmImage: 'TESTVM'

steps:
- task: PowerShell@2
  displayName: 'Printing my name using PowerShell'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Hello, Arshad"